'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    const foods = [
      //Pizza
      { foodName: 'Pizza Napoletana', price: 12.99, rating: 4.7, description: 'Traditional Neapolitan pizza', foodImage: 'default_image_url', categoryId: 1, storeId: 1 },
      { foodName: 'Pizza Margherita', price: 11.99, rating: 4.5, description: 'Classic Margherita pizza', foodImage: 'default_image_url', categoryId: 1, storeId: 2 },
      { foodName: 'Pizza bufalina', price: 13.49, rating: 4.8, description: 'Buffalo mozzarella pizza', foodImage: 'default_image_url', categoryId: 1, storeId: 3 },
      { foodName: 'Pizza capricciosa', price: 12.99, rating: 4.6, description: 'Capricciosa pizza with artichokes', foodImage: 'default_image_url', categoryId: 1, storeId: 4 },
      { foodName: 'Pizzette', price: 10.99, rating: 4.5, description: 'Mini pizzas for a perfect snack', foodImage: 'default_image_url', categoryId: 1, storeId: 5 },
      { foodName: 'Pizza al taglio', price: 11.49, rating: 4.7, description: 'Roman-style pizza by the slice', foodImage: 'default_image_url', categoryId: 1, storeId: 6 },
      { foodName: 'Pizza alla diavola', price: 12.49, rating: 4.5, description: 'Spicy Diavola pizza', foodImage: 'default_image_url', categoryId: 1, storeId: 7 },
      { foodName: 'Pinsa romana', price: 13.99, rating: 4.8, description: 'Traditional Roman pinsa', foodImage: 'default_image_url', categoryId: 1, storeId: 8 },
      { foodName: 'Calzone Pizza', price: 12.99, rating: 4.6, description: 'Stuffed pizza with various fillings', foodImage: 'default_image_url', categoryId: 1, storeId: 9 },
      { foodName: 'Caprese Pizza', price: 11.49, rating: 4.5, description: 'Pizza with fresh mozzarella and tomatoes', foodImage: 'default_image_url', categoryId: 1, storeId: 10 },
      { foodName: 'Pizza Romana', price: 11.99, rating: 4.7, description: 'Roman-style pizza with thin crust', foodImage: 'default_image_url', categoryId: 1, storeId: 1 },
      { foodName: 'Apizza', price: 12.49, rating: 4.8, description: 'New Haven-style pizza', foodImage: 'default_image_url', categoryId: 1, storeId: 2 },
      { foodName: 'Stromboli', price: 10.99, rating: 4.5, description: 'Italian turnover filled with various meats', foodImage: 'default_image_url', categoryId: 1, storeId: 3 },
      { foodName: 'Pizza bianca', price: 12.99, rating: 4.6, description: 'White pizza with ricotta and mozzarella', foodImage: 'default_image_url', categoryId: 1, storeId: 4 },
      { foodName: 'Pizza fritta', price: 11.49, rating: 4.5, description: 'Fried pizza from Naples', foodImage: 'default_image_url', categoryId: 1, storeId: 5 },
      { foodName: 'Fugazzeta', price: 10.99, rating: 4.7, description: 'Stuffed pizza from Argentina', foodImage: 'default_image_url', categoryId: 1, storeId: 6 },
      { foodName: 'Dinnete', price: 11.99, rating: 4.6, description: 'Savory flatbread from Italy', foodImage: 'default_image_url', categoryId: 1, storeId: 7 },
      { foodName: 'Grilled Pizza', price: 12.49, rating: 4.5, description: 'Pizza cooked on a grill for a smoky flavor', foodImage: 'default_image_url', categoryId: 1, storeId: 8 },
      { foodName: 'Sardenara', price: 10.49, rating: 4.5, description: 'Sardinian-style pizza', foodImage: 'default_image_url', categoryId: 1, storeId: 9 },
      { foodName: 'Pizza Viennese', price: 11.49, rating: 4.6, description: 'Austrian-style pizza', foodImage: 'default_image_url', categoryId: 1, storeId: 10 },

      //Burger
      { foodName: 'Burger Joys', price: 9.99, rating: 4.5, description: 'Delicious burgers made with fresh ingredients', foodImage: 'default_image_url', categoryId: 2, storeId: 1 },
      { foodName: 'Zombie Bar', price: 10.49, rating: 4.6, description: 'Themed burger joint with unique flavors', foodImage: 'default_image_url', categoryId: 2, storeId: 2 },
      { foodName: 'Chez Victor', price: 11.99, rating: 4.7, description: 'French-style burgers', foodImage: 'default_image_url', categoryId: 2, storeId: 3 },
      { foodName: 'Easey’s', price: 12.49, rating: 4.5, description: 'Casual eatery known for its tasty burgers', foodImage: 'default_image_url', categoryId: 2, storeId: 4 },
      { foodName: 'JB’s Brewhouse', price: 10.99, rating: 4.8, description: 'Burgers paired with local craft beers', foodImage: 'default_image_url', categoryId: 2, storeId: 5 },
      { foodName: 'Nowon', price: 11.49, rating: 4.6, description: 'Korean-inspired burgers', foodImage: 'default_image_url', categoryId: 2, storeId: 6 },
      { foodName: 'Hoodbuger', price: 10.49, rating: 4.5, description: 'Unique burger combinations', foodImage: 'default_image_url', categoryId: 2, storeId: 7 },
      { foodName: 'Burger Don', price: 11.99, rating: 4.7, description: 'Japanese-style burgers', foodImage: 'default_image_url', categoryId: 2, storeId: 8 },
      { foodName: 'Fergburger', price: 12.99, rating: 4.9, description: 'Famous burger shop with huge portions', foodImage: 'default_image_url', categoryId: 2, storeId: 9 },
      { foodName: 'Pickl', price: 10.99, rating: 4.5, description: 'Fresh ingredients and creative toppings', foodImage: 'default_image_url', categoryId: 2, storeId: 10 },
      { foodName: 'Kabo Burger', price: 11.49, rating: 4.6, description: 'Specialty burgers with unique sauces', foodImage: 'default_image_url', categoryId: 2, storeId: 1 },
      { foodName: 'Bar Luca', price: 12.49, rating: 4.7, description: 'Burgers with a twist', foodImage: 'default_image_url', categoryId: 2, storeId: 2 },
      { foodName: 'Three Buns', price: 10.99, rating: 4.5, description: 'Artisan burgers with high-quality ingredients', foodImage: 'default_image_url', categoryId: 2, storeId: 3 },
      { foodName: 'Smokin’ Joes', price: 11.99, rating: 4.8, description: 'Smoked burgers and delicious sides', foodImage: 'default_image_url', categoryId: 2, storeId: 4 },
      { foodName: 'Bub’s NOLA', price: 12.99, rating: 4.6, description: 'New Orleans-inspired burgers', foodImage: 'default_image_url', categoryId: 2, storeId: 5 },
      { foodName: 'Smash Tag', price: 10.49, rating: 4.5, description: 'Smash burgers with great toppings', foodImage: 'default_image_url', categoryId: 2, storeId: 6 },
      { foodName: 'BAP', price: 11.49, rating: 4.7, description: 'Burgers with creative flavor combinations', foodImage: 'default_image_url', categoryId: 2, storeId: 7 },
      { foodName: 'The Nook', price: 10.99, rating: 4.5, description: 'Cozy spot for great burgers', foodImage: 'default_image_url', categoryId: 2, storeId: 8 },
      { foodName: 'Mother Flipper', price: 12.49, rating: 4.8, description: 'Gourmet burgers and sides', foodImage: 'default_image_url', categoryId: 2, storeId: 9 },
      { foodName: 'Burgermeister', price: 11.99, rating: 4.9, description: 'Classic burgers with a modern twist', foodImage: 'default_image_url', categoryId: 2, storeId: 10 },

      //Noodes
      { foodName: 'Ramen', price: 10.99, rating: 4.6, description: 'Delicious Japanese ramen', foodImage: 'default_image_url', categoryId: 3, storeId: 1 },
      { foodName: 'Laksam', price: 9.99, rating: 4.5, description: 'Traditional Malaysian laksam', foodImage: 'default_image_url', categoryId: 3, storeId: 2 },
      { foodName: 'Khao soi', price: 11.49, rating: 4.7, description: 'Coconut curry noodle soup from Thailand', foodImage: 'default_image_url', categoryId: 3, storeId: 3 },
      { foodName: 'Rechta', price: 10.99, rating: 4.5, description: 'Algerian noodle dish', foodImage: 'default_image_url', categoryId: 3, storeId: 4 },
      { foodName: 'Mee bandung', price: 9.49, rating: 4.6, description: 'Indonesian noodle dish with a spicy sauce', foodImage: 'default_image_url', categoryId: 3, storeId: 5 },
      { foodName: 'Tonkotsu ramen', price: 12.99, rating: 4.8, description: 'Rich and creamy pork bone ramen', foodImage: 'default_image_url', categoryId: 3, storeId: 6 },
      { foodName: 'Miso ramen', price: 11.49, rating: 4.5, description: 'Ramen with miso broth', foodImage: 'default_image_url', categoryId: 3, storeId: 7 },
      { foodName: 'Dan Dan noodles', price: 10.99, rating: 4.6, description: 'Spicy Sichuan noodles', foodImage: 'default_image_url', categoryId: 3, storeId: 8 },
      { foodName: 'Tsukemen', price: 11.99, rating: 4.7, description: 'Dipping noodles served with broth', foodImage: 'default_image_url', categoryId: 3, storeId: 9 },
      { foodName: 'Hakata ramen', price: 12.49, rating: 4.5, description: 'Famous pork bone ramen from Hakata', foodImage: 'default_image_url', categoryId: 3, storeId: 10 },
      { foodName: 'Pho', price: 9.99, rating: 4.8, description: 'Traditional Vietnamese noodle soup', foodImage: 'default_image_url', categoryId: 3, storeId: 1 },
      { foodName: 'Pad Thai', price: 10.49, rating: 4.6, description: 'Famous Thai stir-fried noodles', foodImage: 'default_image_url', categoryId: 3, storeId: 2 },
      { foodName: 'Shoyu ramen', price: 11.49, rating: 4.5, description: 'Soy sauce flavored ramen', foodImage: 'default_image_url', categoryId: 3, storeId: 3 },
      { foodName: 'Shio ramen', price: 10.99, rating: 4.6, description: 'Salt flavored ramen', foodImage: 'default_image_url', categoryId: 3, storeId: 4 },
      { foodName: 'Lagman', price: 11.99, rating: 4.7, description: 'Uzbek noodle dish', foodImage: 'default_image_url', categoryId: 3, storeId: 5 },
      { foodName: 'Laksa', price: 12.49, rating: 4.8, description: 'Spicy noodle soup from Malaysia', foodImage: 'default_image_url', categoryId: 3, storeId: 6 },
      { foodName: 'Udon', price: 10.99, rating: 4.5, description: 'Thick wheat noodles served in broth', foodImage: 'default_image_url', categoryId: 3, storeId: 7 },
      { foodName: 'Curry Mee', price: 11.49, rating: 4.6, description: 'Coconut curry noodle soup', foodImage: 'default_image_url', categoryId: 3, storeId: 8 },
      { foodName: 'Tororo soba', price: 12.99, rating: 4.7, description: 'Soba noodles with grated yam', foodImage: 'default_image_url', categoryId: 3, storeId: 9 },
      { foodName: 'Yakisoba', price: 10.49, rating: 4.5, description: 'Japanese stir-fried noodles', foodImage: 'default_image_url', categoryId: 3, storeId: 10 },

      //Sandwich
      { foodName: 'Tombik Döner', price: 9.99, rating: 4.5, description: 'Turkish döner kebab', foodImage: 'default_image_url', categoryId: 4, storeId: 1 },
      { foodName: 'Shawarma', price: 10.49, rating: 4.6, description: 'Middle Eastern meat wrap', foodImage: 'default_image_url', categoryId: 4, storeId: 2 },
      { foodName: 'Tortas', price: 8.99, rating: 4.7, description: 'Mexican sandwich', foodImage: 'default_image_url', categoryId: 4, storeId: 3 },
      { foodName: 'Lobster Roll', price: 15.99, rating: 4.8, description: 'Delicious lobster in a roll', foodImage: 'default_image_url', categoryId: 4, storeId: 4 },
      { foodName: 'Jibarito', price: 9.49, rating: 4.5, description: 'Puerto Rican sandwich with plantains', foodImage: 'default_image_url', categoryId: 4, storeId: 5 },
      { foodName: 'Reuben', price: 10.99, rating: 4.6, description: 'Corned beef sandwich with sauerkraut', foodImage: 'default_image_url', categoryId: 4, storeId: 6 },
      { foodName: 'Po\'Boy', price: 11.49, rating: 4.7, description: 'Louisiana-style sandwich', foodImage: 'default_image_url', categoryId: 4, storeId: 7 },
      { foodName: 'Cuban Sandwich', price: 9.99, rating: 4.6, description: 'Traditional Cuban sandwich', foodImage: 'default_image_url', categoryId: 4, storeId: 8 },
      { foodName: 'Choripán', price: 8.49, rating: 4.5, description: 'Argentinian sausage sandwich', foodImage: 'default_image_url', categoryId: 4, storeId: 9 },
      { foodName: 'Prego', price: 10.49, rating: 4.6, description: 'Portuguese steak sandwich', foodImage: 'default_image_url', categoryId: 4, storeId: 10 },
      { foodName: 'Svamptoast', price: 8.99, rating: 4.7, description: 'Swedish mushroom toast', foodImage: 'default_image_url', categoryId: 4, storeId: 1 },
      { foodName: 'Bondipan', price: 9.49, rating: 4.5, description: 'Indian sandwich', foodImage: 'default_image_url', categoryId: 4, storeId: 2 },
      { foodName: 'Cheesesteak', price: 10.99, rating: 4.8, description: 'Philadelphia cheesesteak', foodImage: 'default_image_url', categoryId: 4, storeId: 3 },
      { foodName: 'Arepa', price: 8.99, rating: 4.6, description: 'Venezuelan corn cake', foodImage: 'default_image_url', categoryId: 4, storeId: 4 },
      { foodName: 'Butifarra', price: 9.99, rating: 4.5, description: 'Spanish sausage sandwich', foodImage: 'default_image_url', categoryId: 4, storeId: 5 },
      { foodName: 'Montadito', price: 7.99, rating: 4.7, description: 'Spanish tapas sandwich', foodImage: 'default_image_url', categoryId: 4, storeId: 6 },
      { foodName: 'Vada pav', price: 6.99, rating: 4.6, description: 'Indian potato sandwich', foodImage: 'default_image_url', categoryId: 4, storeId: 7 },
      { foodName: 'Chivito', price: 10.49, rating: 4.5, description: 'Uruguayan sandwich with meat and cheese', foodImage: 'default_image_url', categoryId: 4, storeId: 8 },
      { foodName: 'Bifana', price: 9.49, rating: 4.6, description: 'Portuguese pork sandwich', foodImage: 'default_image_url', categoryId: 4, storeId: 9 },
      { foodName: 'Sabich', price: 8.99, rating: 4.7, description: 'Israeli eggplant sandwich', foodImage: 'default_image_url', categoryId: 4, storeId: 10 },

      //Salad
      { foodName: 'Dakos', price: 7.99, rating: 4.5, description: 'Cretan barley rusk salad', foodImage: 'default_image_url', categoryId: 5, storeId: 1 },
      { foodName: 'Mechouia Salad', price: 6.99, rating: 4.6, description: 'Tunisian grilled vegetable salad', foodImage: 'default_image_url', categoryId: 5, storeId: 2 },
      { foodName: 'Greek salad', price: 5.99, rating: 4.7, description: 'Classic Greek salad with feta cheese', foodImage: 'default_image_url', categoryId: 5, storeId: 3 },
      { foodName: 'Caprese Salad', price: 8.49, rating: 4.8, description: 'Fresh mozzarella, tomatoes, and basil', foodImage: 'default_image_url', categoryId: 5, storeId: 4 },
      { foodName: 'Fattoush', price: 7.49, rating: 4.5, description: 'Lebanese salad with toasted bread', foodImage: 'default_image_url', categoryId: 5, storeId: 5 },
      { foodName: 'Shopska salata', price: 6.49, rating: 4.6, description: 'Bulgarian salad with cucumbers and cheese', foodImage: 'default_image_url', categoryId: 5, storeId: 6 },
      { foodName: 'Pecel', price: 8.99, rating: 4.5, description: 'Indonesian vegetable salad with peanut sauce', foodImage: 'default_image_url', categoryId: 5, storeId: 7 },
      { foodName: 'Ketoprak', price: 7.99, rating: 4.7, description: 'Indonesian salad with rice and vegetables', foodImage: 'default_image_url', categoryId: 5, storeId: 8 },
      { foodName: 'Houria', price: 6.99, rating: 4.6, description: 'Tunisian carrot salad', foodImage: 'default_image_url', categoryId: 5, storeId: 9 },
      { foodName: 'Kısır', price: 5.99, rating: 4.5, description: 'Turkish bulgur salad', foodImage: 'default_image_url', categoryId: 5, storeId: 10 },
      { foodName: 'Panzanella', price: 7.49, rating: 4.6, description: 'Italian bread salad', foodImage: 'default_image_url', categoryId: 5, storeId: 1 },
      { foodName: 'Mizeria', price: 6.49, rating: 4.5, description: 'Polish cucumber salad', foodImage: 'default_image_url', categoryId: 5, storeId: 2 },
      { foodName: 'Larb', price: 8.99, rating: 4.7, description: 'Laotian meat salad', foodImage: 'default_image_url', categoryId: 5, storeId: 3 },
      { foodName: 'Piyaz', price: 7.99, rating: 4.6, description: 'Turkish white bean salad', foodImage: 'default_image_url', categoryId: 5, storeId: 4 },
      { foodName: 'Zaalouk', price: 6.99, rating: 4.5, description: 'Moroccan eggplant salad', foodImage: 'default_image_url', categoryId: 5, storeId: 5 },
      { foodName: 'Horta', price: 5.99, rating: 4.6, description: 'Greek wild greens salad', foodImage: 'default_image_url', categoryId: 5, storeId: 6 },
      { foodName: 'Sunomono', price: 6.49, rating: 4.5, description: 'Japanese cucumber salad', foodImage: 'default_image_url', categoryId: 5, storeId: 7 },
      { foodName: 'Phla kung', price: 8.49, rating: 4.8, description: 'Thai shrimp salad', foodImage: 'default_image_url', categoryId: 5, storeId: 8 },
      { foodName: 'Zeytin piyazi', price: 7.49, rating: 4.5, description: 'Turkish olive salad', foodImage: 'default_image_url', categoryId: 5, storeId: 9 },
      { foodName: 'Olivier Salad', price: 9.99, rating: 4.6, description: 'Russian potato salad', foodImage: 'default_image_url', categoryId: 5, storeId: 10 },

      //Pasta
      { foodName: "Pasta 'ncasciata", price: 10.99, rating: 4.5, description: 'Sicilian pasta dish with eggplant', foodImage: 'default_image_url', categoryId: 6, storeId: 1 },
      { foodName: "Pasta carbonara", price: 11.49, rating: 4.6, description: 'Classic Roman pasta with eggs and cheese', foodImage: 'default_image_url', categoryId: 6, storeId: 2 },
      { foodName: "Cacio e pepe", price: 9.99, rating: 4.7, description: 'Pasta with cheese and pepper', foodImage: 'default_image_url', categoryId: 6, storeId: 3 },
      { foodName: "Pasta alla gricia", price: 10.49, rating: 4.5, description: 'Roman pasta with guanciale and cheese', foodImage: 'default_image_url', categoryId: 6, storeId: 4 },
      { foodName: "Ravioli", price: 12.99, rating: 4.8, description: 'Stuffed pasta with various fillings', foodImage: 'default_image_url', categoryId: 6, storeId: 5 },
      { foodName: "Amatriciana", price: 11.99, rating: 4.6, description: 'Pasta with tomato sauce and guanciale', foodImage: 'default_image_url', categoryId: 6, storeId: 6 },
      { foodName: "Pastitsio", price: 13.49, rating: 4.5, description: 'Greek pasta baked with meat and béchamel', foodImage: 'default_image_url', categoryId: 6, storeId: 7 },
      { foodName: "Agnolotti", price: 12.49, rating: 4.6, description: 'Pasta pockets filled with meat or vegetables', foodImage: 'default_image_url', categoryId: 6, storeId: 8 },
      { foodName: "Trofie al pesto", price: 10.99, rating: 4.5, description: 'Short twisted pasta with basil pesto', foodImage: 'default_image_url', categoryId: 6, storeId: 9 },
      { foodName: "Giouvetsi", price: 11.99, rating: 4.6, description: 'Greek dish of pasta and meat in tomato sauce', foodImage: 'default_image_url', categoryId: 6, storeId: 10 },
      { foodName: "Mezzelune", price: 12.99, rating: 4.5, description: 'Half-moon shaped stuffed pasta', foodImage: 'default_image_url', categoryId: 6, storeId: 1 },
      { foodName: "Tortellini", price: 13.49, rating: 4.6, description: 'Stuffed pasta rings, often served in broth', foodImage: 'default_image_url', categoryId: 6, storeId: 2 },
      { foodName: "Tortelli", price: 12.49, rating: 4.5, description: 'Stuffed pasta similar to ravioli, often larger', foodImage: 'default_image_url', categoryId: 6, storeId: 3 },
      { foodName: "Pasta e ceci", price: 9.99, rating: 4.5, description: 'Pasta with chickpeas, a classic Italian dish', foodImage: 'default_image_url', categoryId: 6, storeId: 4 },
      { foodName: "Paglia e fieno", price: 10.49, rating: 4.6, description: 'Pasta made with spinach and egg dough', foodImage: 'default_image_url', categoryId: 6, storeId: 5 },
      { foodName: "Pasta al limone", price: 11.49, rating: 4.7, description: 'Pasta with a fresh lemon sauce', foodImage: 'default_image_url', categoryId: 6, storeId: 6 },
      { foodName: "Cjarsons", price: 12.99, rating: 4.5, description: 'Stuffed pasta from the Friuli region', foodImage: 'default_image_url', categoryId: 6, storeId: 7 },
      { foodName: "Pastitsada", price: 13.49, rating: 4.6, description: 'Greek pasta with meat in a rich sauce', foodImage: 'default_image_url', categoryId: 6, storeId: 8 },
      { foodName: "Baked Ziti", price: 11.99, rating: 4.5, description: 'Pasta baked with cheese and tomato sauce', foodImage: 'default_image_url', categoryId: 6, storeId: 9 },
      { foodName: "Fideuà", price: 12.49, rating: 4.6, description: 'Spanish noodle dish similar to paella', foodImage: 'default_image_url', categoryId: 6, storeId: 10 },

      //Rice
      { foodName: "Kaisendon", price: 14.99, rating: 4.6, description: 'Sushi rice topped with fresh sashimi and seafood', foodImage: 'default_image_url', categoryId: 7, storeId: 1 },
      { foodName: "Nasi goreng", price: 10.99, rating: 4.5, description: 'Indonesian fried rice with vegetables and chicken', foodImage: 'default_image_url', categoryId: 7, storeId: 2 },
      { foodName: "Khao phat", price: 10.49, rating: 4.6, description: 'Thai fried rice with vegetables and protein', foodImage: 'default_image_url', categoryId: 7, storeId: 3 },
      { foodName: "Diri ak pwa", price: 11.49, rating: 4.5, description: 'Haitian rice and beans', foodImage: 'default_image_url', categoryId: 7, storeId: 4 },
      { foodName: "Nigiri", price: 12.99, rating: 4.7, description: 'Hand-formed rice topped with fresh fish', foodImage: 'default_image_url', categoryId: 7, storeId: 5 },
      { foodName: "Broken Rice", price: 10.99, rating: 4.6, description: 'Vietnamese dish of broken rice with grilled meats', foodImage: 'default_image_url', categoryId: 7, storeId: 6 },
      { foodName: "Bubur ayam", price: 9.99, rating: 4.5, description: 'Indonesian chicken porridge', foodImage: 'default_image_url', categoryId: 7, storeId: 7 },
      { foodName: "Tekkadon", price: 13.49, rating: 4.8, description: 'Rice bowl topped with grilled fish', foodImage: 'default_image_url', categoryId: 7, storeId: 8 },
      { foodName: "Negitorodon", price: 12.49, rating: 4.6, description: 'Rice bowl with grilled beef and green onions', foodImage: 'default_image_url', categoryId: 7, storeId: 9 },
      { foodName: "Risotto", price: 11.99, rating: 4.5, description: 'Creamy Italian rice dish cooked with broth', foodImage: 'default_image_url', categoryId: 7, storeId: 10 },
      { foodName: "Tendon", price: 12.99, rating: 4.7, description: 'Tempura on rice with sauce', foodImage: 'default_image_url', categoryId: 7, storeId: 1 },
      { foodName: "Katsudon", price: 13.49, rating: 4.6, description: 'Breaded pork cutlet on rice with egg', foodImage: 'default_image_url', categoryId: 7, storeId: 2 },
      { foodName: "Chirashizushi", price: 14.49, rating: 4.5, description: 'Scattered sushi bowl with various toppings', foodImage: 'default_image_url', categoryId: 7, storeId: 3 },
      { foodName: "Tahchin", price: 12.49, rating: 4.6, description: 'Persian rice cake with saffron and chicken', foodImage: 'default_image_url', categoryId: 7, storeId: 4 },
      { foodName: "Nasi uduk", price: 10.99, rating: 4.5, description: 'Indonesian coconut rice', foodImage: 'default_image_url', categoryId: 7, storeId: 5 },
      { foodName: "Gunkanmaki", price: 11.49, rating: 4.7, description: 'Seaweed-wrapped sushi rice topped with ingredients', foodImage: 'default_image_url', categoryId: 7, storeId: 6 },
      { foodName: "Paella", price: 14.99, rating: 4.8, description: 'Spanish rice dish with seafood and saffron', foodImage: 'default_image_url', categoryId: 7, storeId: 7 },
      { foodName: "Onigiri", price: 9.99, rating: 4.5, description: 'Japanese rice balls often filled with ingredients', foodImage: 'default_image_url', categoryId: 7, storeId: 8 },
      { foodName: "Biryani", price: 12.99, rating: 4.7, description: 'Spiced rice dish with meat and vegetables', foodImage: 'default_image_url', categoryId: 7, storeId: 9 },
      { foodName: "Bibimbap", price: 11.99, rating: 4.6, description: 'Korean mixed rice with vegetables and meat', foodImage: 'default_image_url', categoryId: 7, storeId: 10 },

      //Dessert
      { foodName: "Pastel de nata", price: 4.99, rating: 4.6, description: 'Portuguese custard tart with a flaky crust', foodImage: 'default_image_url', categoryId: 8, storeId: 1 },
      { foodName: "Dondurma", price: 3.99, rating: 4.5, description: 'Turkish ice cream with a stretchy texture', foodImage: 'default_image_url', categoryId: 8, storeId: 2 },
      { foodName: "Tespishte", price: 5.49, rating: 4.7, description: 'Traditional Turkish sweet treat', foodImage: 'default_image_url', categoryId: 8, storeId: 3 },
      { foodName: "Tiramisù", price: 6.99, rating: 4.8, description: 'Italian coffee-flavored dessert', foodImage: 'default_image_url', categoryId: 8, storeId: 4 },
      { foodName: "Crêpes", price: 4.49, rating: 4.5, description: 'Thin French pancakes with various fillings', foodImage: 'default_image_url', categoryId: 8, storeId: 5 },
      { foodName: "Crème brûlée", price: 5.99, rating: 4.6, description: 'Rich custard topped with caramelized sugar', foodImage: 'default_image_url', categoryId: 8, storeId: 6 },
      { foodName: "Dulce de leche", price: 3.49, rating: 4.5, description: 'Sweetened condensed milk caramel', foodImage: 'default_image_url', categoryId: 8, storeId: 7 },
      { foodName: "Sernik", price: 4.99, rating: 4.6, description: 'Polish cheesecake made with twaróg', foodImage: 'default_image_url', categoryId: 8, storeId: 8 },
      { foodName: "Tinginys", price: 3.99, rating: 4.4, description: 'Lithuanian sweet dumplings', foodImage: 'default_image_url', categoryId: 8, storeId: 9 },
      { foodName: "Klepon", price: 2.99, rating: 4.5, description: 'Indonesian rice cake balls filled with palm sugar', foodImage: 'default_image_url', categoryId: 8, storeId: 10 },
      { foodName: "Bionico", price: 4.99, rating: 4.6, description: 'Mexican fruit salad with cream and nuts', foodImage: 'default_image_url', categoryId: 8, storeId: 1 },
      { foodName: "Baklava", price: 5.49, rating: 4.7, description: 'Sweet pastry made of layers of filo filled with nuts and honey', foodImage: 'default_image_url', categoryId: 8, storeId: 2 },
      { foodName: "Alfajores", price: 4.49, rating: 4.5, description: 'Peruvian cookies filled with dulce de leche', foodImage: 'default_image_url', categoryId: 8, storeId: 3 },
      { foodName: "Apfelstrudel", price: 5.99, rating: 4.6, description: 'Austrian pastry filled with spiced apples', foodImage: 'default_image_url', categoryId: 8, storeId: 4 },
      { foodName: "Stroopwafel", price: 3.99, rating: 4.5, description: 'Dutch syrup waffle cookies', foodImage: 'default_image_url', categoryId: 8, storeId: 5 },
      { foodName: "Appeltaart", price: 4.99, rating: 4.6, description: 'Dutch apple pie with a flaky crust', foodImage: 'default_image_url', categoryId: 8, storeId: 6 },
      { foodName: "Liège Waffle", price: 4.49, rating: 4.7, description: 'Belgian waffle with caramelized sugar', foodImage: 'default_image_url', categoryId: 8, storeId: 7 },
      { foodName: "Kaju katli", price: 5.49, rating: 4.8, description: 'Indian cashew fudge', foodImage: 'default_image_url', categoryId: 8, storeId: 8 },
      { foodName: "Túró rudi", price: 2.99, rating: 4.4, description: 'Hungarian chocolate-covered curd snack', foodImage: 'default_image_url', categoryId: 8, storeId: 9 },
      { foodName: "Papanași", price: 5.99, rating: 4.6, description: 'Romanian cheese doughnuts with sour cream and jam', foodImage: 'default_image_url', categoryId: 8, storeId: 10 },

      //Soup
      { foodName: "Vori-vori", price: 4.99, rating: 4.6, description: 'Traditional Indonesian soup with dumplings', foodImage: 'default_image_url', categoryId: 9, storeId: 1 },
      { foodName: "Soto Betawi", price: 5.49, rating: 4.7, description: 'Jakarta-style beef soup', foodImage: 'default_image_url', categoryId: 9, storeId: 2 },
      { foodName: "Rawon", price: 6.99, rating: 4.8, description: 'East Javanese black beef soup', foodImage: 'default_image_url', categoryId: 9, storeId: 3 },
      { foodName: "Sopa Tarasca", price: 4.99, rating: 4.5, description: 'Mexican soup with chicken, tomatoes, and chilies', foodImage: 'default_image_url', categoryId: 9, storeId: 4 },
      { foodName: "Pozole", price: 5.49, rating: 4.6, description: 'Mexican hominy soup with meat', foodImage: 'default_image_url', categoryId: 9, storeId: 5 },
      { foodName: "Sinigang", price: 6.49, rating: 4.7, description: 'Filipino sour soup with meat and vegetables', foodImage: 'default_image_url', categoryId: 9, storeId: 6 },
      { foodName: "Gulai", price: 5.99, rating: 4.6, description: 'Indonesian coconut curry soup', foodImage: 'default_image_url', categoryId: 9, storeId: 7 },
      { foodName: "Gamjatang", price: 7.49, rating: 4.8, description: 'Korean spicy pork bone soup', foodImage: 'default_image_url', categoryId: 9, storeId: 8 },
      { foodName: "Tacacá", price: 4.99, rating: 4.5, description: 'Brazilian soup with jambu and shrimp', foodImage: 'default_image_url', categoryId: 9, storeId: 9 },
      { foodName: "Cullen Skink", price: 5.49, rating: 4.6, description: 'Scottish smoked haddock soup', foodImage: 'default_image_url', categoryId: 9, storeId: 10 },
      { foodName: "Chorba beïda", price: 4.49, rating: 4.5, description: 'Algerian white soup with chickpeas', foodImage: 'default_image_url', categoryId: 9, storeId: 1 },
      { foodName: "Tom yum", price: 5.99, rating: 4.7, description: 'Spicy Thai soup with shrimp and herbs', foodImage: 'default_image_url', categoryId: 9, storeId: 2 },
      { foodName: "Bulalô", price: 6.49, rating: 4.8, description: 'Filipino beef bone marrow soup', foodImage: 'default_image_url', categoryId: 9, storeId: 3 },
      { foodName: "Youvarlakia", price: 5.49, rating: 4.6, description: 'Greek meatball soup', foodImage: 'default_image_url', categoryId: 9, storeId: 4 },
      { foodName: "Laksam", price: 4.99, rating: 4.5, description: 'Malay spicy fish soup', foodImage: 'default_image_url', categoryId: 9, storeId: 5 },
      { foodName: "Bela čorba", price: 5.49, rating: 4.6, description: 'Serbian white soup', foodImage: 'default_image_url', categoryId: 9, storeId: 6 },
      { foodName: "Gumbo", price: 6.99, rating: 4.8, description: 'Louisiana stew with meat and vegetables', foodImage: 'default_image_url', categoryId: 9, storeId: 7 },
      { foodName: "Soto", price: 4.99, rating: 4.6, description: 'Indonesian traditional soup', foodImage: 'default_image_url', categoryId: 9, storeId: 8 },
      { foodName: "Oden", price: 5.49, rating: 4.7, description: 'Japanese winter soup with various ingredients', foodImage: 'default_image_url', categoryId: 9, storeId: 9 },
      { foodName: "Paomo", price: 6.49, rating: 4.8, description: 'Chinese bread soup with lamb', foodImage: 'default_image_url', categoryId: 9, storeId: 10 },

      //Drink
      { foodName: "Coca", price: 1.49, rating: 4.5, description: 'Classic cola beverage', foodImage: 'default_image_url', categoryId: 10, storeId: 1 },
      { foodName: "Pepsi", price: 1.49, rating: 4.4, description: 'Popular cola drink', foodImage: 'default_image_url', categoryId: 10, storeId: 2 },
      { foodName: "Fanta", price: 1.49, rating: 4.3, description: 'Fruity orange soda', foodImage: 'default_image_url', categoryId: 10, storeId: 3 },
      { foodName: "Tiger Beer", price: 2.49, rating: 4.6, description: 'Popular Asian beer', foodImage: 'default_image_url', categoryId: 10, storeId: 4 },
      { foodName: "Milk", price: 0.99, rating: 4.5, description: 'Fresh dairy milk', foodImage: 'default_image_url', categoryId: 10, storeId: 5 },
      { foodName: "7up", price: 1.49, rating: 4.2, description: 'Lemon-lime flavored soda', foodImage: 'default_image_url', categoryId: 10, storeId: 6 },
      { foodName: "Sprite", price: 1.49, rating: 4.3, description: 'Lemon-lime soda', foodImage: 'default_image_url', categoryId: 10, storeId: 7 },
      { foodName: "Mirinda", price: 1.49, rating: 4.4, description: 'Fruit-flavored soft drink', foodImage: 'default_image_url', categoryId: 10, storeId: 8 },
      { foodName: "Mountain Dew", price: 1.49, rating: 4.5, description: 'Citrus-flavored soda', foodImage: 'default_image_url', categoryId: 10, storeId: 9 },
      { foodName: "Orange juice", price: 2.99, rating: 4.7, description: 'Freshly squeezed orange juice', foodImage: 'default_image_url', categoryId: 10, storeId: 10 },
      { foodName: "Carrot juice", price: 2.49, rating: 4.6, description: 'Nutritious carrot juice', foodImage: 'default_image_url', categoryId: 10, storeId: 1 },
      { foodName: "Tomato juice", price: 2.49, rating: 4.5, description: 'Healthy tomato juice', foodImage: 'default_image_url', categoryId: 10, storeId: 2 },
      { foodName: "Apple juice", price: 2.99, rating: 4.8, description: 'Fresh apple juice', foodImage: 'default_image_url', categoryId: 10, storeId: 3 },
      { foodName: "Grapefruit juice", price: 2.99, rating: 4.7, description: 'Tart grapefruit juice', foodImage: 'default_image_url', categoryId: 10, storeId: 4 },
      { foodName: "Pineapple juice", price: 2.99, rating: 4.6, description: 'Sweet pineapple juice', foodImage: 'default_image_url', categoryId: 10, storeId: 5 },
      { foodName: "Grape juice", price: 2.99, rating: 4.5, description: 'Refreshing grape juice', foodImage: 'default_image_url', categoryId: 10, storeId: 6 },
      { foodName: "Guava juice", price: 2.99, rating: 4.7, description: 'Tropical guava juice', foodImage: 'default_image_url', categoryId: 10, storeId: 7 },
      { foodName: "Ambarella juice", price: 3.49, rating: 4.8, description: 'Unique ambarella juice', foodImage: 'default_image_url', categoryId: 10, storeId: 8 },
      { foodName: "Pomegranate juice", price: 3.49, rating: 4.8, description: 'Rich pomegranate juice', foodImage: 'default_image_url', categoryId: 10, storeId: 9 },
      { foodName: "Mango Juice", price: 3.49, rating: 4.9, description: 'Sweet mango juice', foodImage: 'default_image_url', categoryId: 10, storeId: 10 },
    ];

    return queryInterface.bulkInsert('foods', foods.map(food => ({
      ...food,
      createdAt: new Date(),
      updatedAt: new Date()
    })), {});
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('foods', null, {});
  }
};
